# Generated by Django 4.2 on 2023-04-27 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_workflow_type', models.CharField(choices=[('strict', 'strict'), ('open', 'open')], default='open', max_length=10)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueWorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_workflow_stage_type', models.CharField(choices=[('all', 'all'), ('one', 'one')], default='all', max_length=5)),
                ('issue_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.issueworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='IssueWorkflowStageApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(choices=[('reviewing', 'reviewing'), ('approved', 'approved'), ('rejected', 'rejected')], default='reviewing', max_length=50, protected=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue_workflow_stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.issueworkflowstage')),
            ],
        ),
    ]
