# Generated by Django 4.2 on 2023-04-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0011_alter_process_id_alter_task_id'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorldProcess',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
