# Generated by Django 4.2 on 2023-04-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_issueworkflow_issueworkflowstage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueworkflowstageapproval',
            old_name='issue_workflow_stage_id',
            new_name='issue_workflow_stage',
        ),
    ]
