# Generated by Django 4.2 on 2023-04-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_rename_issue_workflow_stage_id_issueworkflowstageapproval_issue_workflow_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueworkflowstage',
            name='previous_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='snippets.issueworkflowstage'),
        ),
    ]
