# Generated by Django 4.2 on 2023-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_rename_issue_workflow_issue_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('issue', 'step')},
        ),
        migrations.AlterField(
            model_name='workflow',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
