# Generated by Django 4.2 on 2023-04-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_issueworkflowstage_previous_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
