# Generated by Django 4.2 on 2023-04-25 01:36

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_rename_issue_id_workflow_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='workflow_state',
            field=django_fsm.FSMField(default=0.0, max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='step',
            field=models.FloatField(default=1.0),
        ),
    ]
