# Generated by Django 4.2 on 2023-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_delete_blogpost_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueworkflowstage',
            name='state',
            field=models.CharField(choices=[('reviewing', 'reviewing'), ('approved', 'approved'), ('rejected', 'rejected')], default='reviewing', max_length=10),
        ),
    ]
