# Generated by Django 4.2 on 2023-04-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_issue_workflow_state_alter_workflow_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
