# Generated by Django 4.2 on 2023-05-02 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0006_issuethread'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuethread',
            name='originator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_thread_originator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
