# Generated by Django 4.2 on 2023-05-02 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0008_issuecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issuer',
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='content',
            field=models.TextField(default='some_content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='json',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
