# Generated by Django 4.2 on 2023-05-02 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0009_remove_issue_issuer_issue_assignee_issue_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecomment',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='issuethread',
            name='originator',
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_thread_comment_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuethread',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_thread_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
